version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: boxful-mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

    volumes:
      - mongodb_data:/data/db
    networks:
      - boxful-network

  app:
    build: .
    container_name: boxful-api
    restart: unless-stopped
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - boxful-network

volumes:
  mongodb_data:

networks:
  boxful-network:
    driver: bridge
